# Generated by Django 4.2.11 on 2025-09-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0002_transportcost'),
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('cheap_ratio', models.FloatField()),
                ('standard_ratio', models.FloatField()),
                ('premium_ratio', models.FloatField()),
                ('price_factor', models.FloatField()),
                ('production_volume', models.FloatField()),
                ('quality_focus', models.FloatField()),
                ('marketing_budget', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
            options={
                'unique_together': {('session', 'strategy')},
            },
        ),
        migrations.CreateModel(
            name='MarketDynamicsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('description', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
            options={
                'unique_together': {('session', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='BikeTypePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=50)),
                ('bike_type_name', models.CharField(max_length=100)),
                ('preference', models.FloatField()),
                ('production_probability', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
            options={
                'unique_together': {('session', 'strategy', 'bike_type_name')},
            },
        ),
    ]
