# Generated by Django 4.2.11 on 2025-09-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_strategyconfiguration_marketdynamicssettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorproduction',
            name='months_in_inventory',
            field=models.IntegerField(default=0, help_text='Age of inventory in months'),
        ),
        migrations.AddField(
            model_name='competitorproduction',
            name='quantity_in_inventory',
            field=models.IntegerField(default=0, help_text='Unsold bikes remaining in inventory'),
        ),
        migrations.AddField(
            model_name='marketcompetition',
            name='actual_sales_volume',
            field=models.IntegerField(default=0, help_text='Actual bikes sold this period'),
        ),
        migrations.AddField(
            model_name='marketcompetition',
            name='demand_curve_elasticity',
            field=models.FloatField(default=1.0, help_text='Price elasticity of demand'),
        ),
        migrations.AddField(
            model_name='marketcompetition',
            name='maximum_market_volume',
            field=models.IntegerField(default=0, help_text='Maximum sales possible in this market segment'),
        ),
        migrations.AddField(
            model_name='marketcompetition',
            name='optimal_price_point',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price that maximizes volume', max_digits=8),
        ),
    ]
