# Generated by Django 4.2.11 on 2025-09-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_sofortkredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='bikes_produced_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='bikes_sold_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='detailed_transactions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='procurement_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='production_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='sales_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='total_procurement_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='total_production_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='total_sales_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
