# Generated by Django 4.2.11 on 2025-10-27 08:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multiplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayergame',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to this game by Spielleitung', related_name='assigned_multiplayer_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GameParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_demand_multiplier', models.FloatField(default=1.0, help_text='Multiplier for overall market demand (0.5 = 50% demand, 2.0 = 200% demand)')),
                ('seasonal_effects_enabled', models.BooleanField(default=True, help_text='Enable seasonal demand fluctuations')),
                ('inflation_rate', models.FloatField(default=0.02, help_text='Annual inflation rate (0.02 = 2%)')),
                ('interest_rate', models.FloatField(default=0.05, help_text='Interest rate for loans (0.05 = 5%)')),
                ('component_cost_multiplier', models.FloatField(default=1.0, help_text='Multiplier for component costs')),
                ('worker_cost_multiplier', models.FloatField(default=1.0, help_text='Multiplier for worker wages')),
                ('transport_cost_multiplier', models.FloatField(default=1.0, help_text='Multiplier for transport costs')),
                ('warehouse_cost_multiplier', models.FloatField(default=1.0, help_text='Multiplier for warehouse rental costs')),
                ('competitor_aggressiveness', models.FloatField(default=1.0, help_text='How aggressive AI competitors are (0.1 = passive, 2.0 = very aggressive)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2.0)])),
                ('custom_parameters', models.JSONField(blank=True, default=dict, help_text='Additional custom parameters in JSON format')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('modification_history', models.JSONField(default=list, help_text='History of parameter changes')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_game_parameters', to=settings.AUTH_USER_MODEL)),
                ('multiplayer_game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='multiplayer.multiplayergame')),
            ],
        ),
    ]
