# Generated by Django 4.2.11 on 2025-10-30 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0002_multiplayergame_assigned_users_gameparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayergame',
            name='last_turn_processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the last turn was processed', null=True),
        ),
        migrations.AddField(
            model_name='multiplayergame',
            name='turn_duration_minutes',
            field=models.IntegerField(default=0, help_text='Minimum wait time in minutes before next turn can be processed (0 = instant)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
