# Generated by Django 4.2.11 on 2025-11-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0004_turnstate_sales_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayergame',
            name='parameters_file',
            field=models.FileField(blank=True, help_text='ZIP file containing game parameters (Excel files)', null=True, upload_to='multiplayer_parameters/'),
        ),
        migrations.AddField(
            model_name='multiplayergame',
            name='parameters_uploaded',
            field=models.BooleanField(default=False, help_text='Whether game parameters have been uploaded and initialized'),
        ),
        migrations.AddField(
            model_name='multiplayergame',
            name='parameters_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When parameters were uploaded', null=True),
        ),
    ]
