# Generated by Django 4.2.11 on 2025-11-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0005_multiplayergame_parameters_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameparameters',
            name='bike_price_cheap_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for cheap/budget bike segment base prices (1.0 = normal)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='bike_price_premium_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for premium bike segment base prices (1.0 = normal)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='bike_price_standard_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for standard bike segment base prices (1.0 = normal)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='bike_skilled_worker_hours_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for skilled worker hours needed per bike (1.0 = normal, 0.8 = 20% faster)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='bike_storage_space_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for bike storage space requirements (1.0 = normal, 0.8 = 20% more compact)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='bike_unskilled_worker_hours_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for unskilled worker hours needed per bike (1.0 = normal, 0.8 = 20% faster)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='competitor_efficiency_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for competitor efficiency (1.0 = normal, 1.2 = competitors 20% more efficient)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='competitor_financial_resources_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for competitor starting capital (1.0 = normal, 0.5 = weaker competitors)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='competitor_market_presence_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for competitor market share (1.0 = normal, 0.8 = competitors have less market share)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='competitor_marketing_budget_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for competitor marketing budgets (1.0 = normal)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='component_storage_space_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for component storage space requirements (1.0 = normal, 0.8 = 20% more compact)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='loan_availability_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for maximum loan amounts available (1.0 = normal)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='market_distance_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for market distances (affects transport costs, 1.0 = normal)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='market_price_sensitivity_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for market price sensitivity (1.0 = normal, 1.5 = customers more price-sensitive)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='other_costs_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for miscellaneous/overhead costs (1.0 = normal, 1.2 = 20% higher costs)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='start_capital_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for starting capital (1.0 = normal, 1.5 = 50% more starting money)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='supplier_complaint_probability_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for supplier complaint probability (1.0 = normal, 0.5 = fewer complaints)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='supplier_complaint_quantity_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for quantity of defective components (1.0 = normal)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='supplier_delivery_time_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for supplier delivery time in days (1.0 = normal, 2.0 = double delivery time)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='supplier_payment_terms_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for supplier payment terms in days (1.0 = normal, 0.5 = half payment terms)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='warehouse_capacity_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for warehouse storage capacity (1.0 = normal, 1.5 = 50% more capacity)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='worker_hours_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for available worker hours per month (1.0 = normal, 1.2 = 20% more hours)'),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='worker_productivity_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for worker productivity (1.0 = normal, 1.2 = 20% more productive)'),
        ),
        migrations.AlterField(
            model_name='gameparameters',
            name='component_cost_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for component costs from suppliers (1.0 = normal, 1.5 = 50% more expensive)'),
        ),
        migrations.AlterField(
            model_name='gameparameters',
            name='inflation_rate',
            field=models.FloatField(default=0.02, help_text='Annual inflation rate affecting costs and prices (0.02 = 2%)'),
        ),
        migrations.AlterField(
            model_name='gameparameters',
            name='interest_rate',
            field=models.FloatField(default=0.05, help_text='Interest rate for loans (0.05 = 5% annual interest)'),
        ),
        migrations.AlterField(
            model_name='gameparameters',
            name='transport_cost_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for transport costs to markets (1.0 = normal, 1.5 = 50% more expensive)'),
        ),
        migrations.AlterField(
            model_name='gameparameters',
            name='warehouse_cost_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for warehouse rental costs per month (1.0 = normal, 2.0 = double rent)'),
        ),
        migrations.AlterField(
            model_name='gameparameters',
            name='worker_cost_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier for worker wages (hourly wage, 1.0 = normal, 1.2 = 20% higher wages)'),
        ),
    ]
