# Generated by Django 4.2.11 on 2025-11-26 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0006_add_comprehensive_game_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplayergame',
            name='turn_deadline_hours',
            field=models.IntegerField(default=24, help_text='Hours to submit decisions. Set to 0 for instant turn advancement when all players submit.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
