# Generated by Django 4.2.11 on 2025-10-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity_m2', models.FloatField(help_text='Lagerkapazität in m²')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Einmaliger Kaufpreis', max_digits=10)),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Monatliche Mietkosten', max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Sortierreihenfolge')),
            ],
            options={
                'ordering': ['order', 'capacity_m2'],
            },
        ),
    ]
