# Generated by Django 4.2.11 on 2025-10-30 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0005_worker_tracking_month_worker_tracking_year_and_more'),
        ('warehouse', '0002_warehousetype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='componentstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='componentstock',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier this component was purchased from (determines quality)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikeshop.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='componentstock',
            unique_together={('session', 'warehouse', 'component', 'supplier')},
        ),
    ]
