# Generated by Django 4.2.7 on 2025-06-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikeshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_months', models.IntegerField(default=24)),
                ('seasonal_effects', models.BooleanField(default=True)),
                ('market_trends', models.BooleanField(default=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
        ),
    ]
