# Generated by Django 4.2.7 on 2025-06-02 04:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikeshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_segment', models.CharField(choices=[('cheap', 'Günstig'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('quantity_planned', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_produced', models.IntegerField(default=0)),
                ('bike_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.biketype')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='ProducedBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_segment', models.CharField(choices=[('cheap', 'Günstig'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('production_month', models.IntegerField()),
                ('production_year', models.IntegerField()),
                ('is_sold', models.BooleanField(default=False)),
                ('production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bike_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.biketype')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
        ),
    ]
