# Generated by Django 4.2.11 on 2025-09-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producedbike',
            name='months_in_inventory',
            field=models.IntegerField(default=0, help_text='How many months this bike has been in inventory'),
        ),
        migrations.AddField(
            model_name='producedbike',
            name='storage_cost_accumulated',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Accumulated storage costs', max_digits=8),
        ),
    ]
