# Generated by Django 4.2.11 on 2025-10-06 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('help_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userhelpprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userhelpprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='help_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
