# Generated by Django 4.2.7 on 2025-06-02 04:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('current_month', models.IntegerField(default=1)),
                ('current_year', models.IntegerField(default=2024)),
                ('balance', models.DecimalField(decimal_places=2, default=80000.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_terms', models.IntegerField(default=30)),
                ('delivery_time', models.IntegerField(default=30)),
                ('complaint_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('complaint_quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quality', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('storage_space_per_unit', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.componenttype')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='BikeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('skilled_worker_hours', models.FloatField()),
                ('unskilled_worker_hours', models.FloatField()),
                ('storage_space_per_unit', models.FloatField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes_frame', to='bikeshop.component')),
                ('gearshift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes_gearshift', to='bikeshop.component')),
                ('handlebar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes_handlebar', to='bikeshop.component')),
                ('motor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bikes_motor', to='bikeshop.component')),
                ('saddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes_saddle', to='bikeshop.component')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
                ('wheel_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes_wheel', to='bikeshop.component')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_type', models.CharField(choices=[('skilled', 'Facharbeiter'), ('unskilled', 'Hilfsarbeiter')], max_length=20)),
                ('hourly_wage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monthly_hours', models.IntegerField(default=150)),
                ('count', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
            options={
                'unique_together': {('session', 'worker_type')},
            },
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.component')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.supplier')),
            ],
            options={
                'unique_together': {('session', 'supplier', 'component')},
            },
        ),
        migrations.CreateModel(
            name='BikePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_segment', models.CharField(choices=[('cheap', 'Günstig'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bike_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.biketype')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
            options={
                'unique_together': {('session', 'bike_type', 'price_segment')},
            },
        ),
    ]
