# Generated by Django 4.2.11 on 2025-09-17 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(max_length=50)),
                ('cost_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('base_transport_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimum_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
            options={
                'unique_together': {('session', 'transport_type')},
            },
        ),
    ]
