# Generated by Django 4.2.11 on 2025-09-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0002_transportcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='biketype',
            name='required_frame_names',
            field=models.JSONField(blank=True, default=list, help_text='List of frame component names this bike can use'),
        ),
        migrations.AddField(
            model_name='biketype',
            name='required_gearshift_names',
            field=models.JSONField(blank=True, default=list, help_text='List of gearshift component names this bike can use'),
        ),
        migrations.AddField(
            model_name='biketype',
            name='required_handlebar_names',
            field=models.JSONField(blank=True, default=list, help_text='List of handlebar component names this bike can use'),
        ),
        migrations.AddField(
            model_name='biketype',
            name='required_motor_names',
            field=models.JSONField(blank=True, default=list, help_text='List of motor component names this bike can use (empty if no motor needed)'),
        ),
        migrations.AddField(
            model_name='biketype',
            name='required_saddle_names',
            field=models.JSONField(blank=True, default=list, help_text='List of saddle component names this bike can use'),
        ),
        migrations.AddField(
            model_name='biketype',
            name='required_wheel_set_names',
            field=models.JSONField(blank=True, default=list, help_text='List of wheel set component names this bike can use'),
        ),
        migrations.AlterField(
            model_name='biketype',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bikes_frame', to='bikeshop.component'),
        ),
        migrations.AlterField(
            model_name='biketype',
            name='gearshift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bikes_gearshift', to='bikeshop.component'),
        ),
        migrations.AlterField(
            model_name='biketype',
            name='handlebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bikes_handlebar', to='bikeshop.component'),
        ),
        migrations.AlterField(
            model_name='biketype',
            name='saddle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bikes_saddle', to='bikeshop.component'),
        ),
        migrations.AlterField(
            model_name='biketype',
            name='wheel_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bikes_wheel', to='bikeshop.component'),
        ),
    ]
