# Generated by Django 4.2.11 on 2025-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0004_auto_20250918_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='tracking_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='tracking_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='used_hours_this_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
