# Generated by Django 4.2.11 on 2025-11-27 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0007_add_turn_deadline_validator_and_help_text'),
        ('bikeshop', '0005_worker_tracking_month_worker_tracking_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='multiplayer_game',
            field=models.ForeignKey(blank=True, help_text='The multiplayer game this session belongs to (null for singleplayer)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='multiplayer.multiplayergame'),
        ),
    ]
