# Generated by Django 4.2.11 on 2025-11-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0006_add_multiplayer_game_to_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='biketype',
            name='skilled_worker_hours',
        ),
        migrations.RemoveField(
            model_name='biketype',
            name='storage_space_per_unit',
        ),
        migrations.RemoveField(
            model_name='biketype',
            name='unskilled_worker_hours',
        ),
        migrations.RemoveField(
            model_name='supplierprice',
            name='price',
        ),
        migrations.AddField(
            model_name='bikeprice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price without multipliers', max_digits=8),
        ),
        migrations.AddField(
            model_name='biketype',
            name='base_skilled_worker_hours',
            field=models.FloatField(default=0, help_text='Base skilled worker hours without multipliers'),
        ),
        migrations.AddField(
            model_name='biketype',
            name='base_storage_space_per_unit',
            field=models.FloatField(default=0, help_text='Base storage space without multipliers'),
        ),
        migrations.AddField(
            model_name='biketype',
            name='base_unskilled_worker_hours',
            field=models.FloatField(default=0, help_text='Base unskilled worker hours without multipliers'),
        ),
        migrations.AddField(
            model_name='supplierprice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price without multipliers', max_digits=8),
        ),
    ]
