# Generated by Django 4.2.7 on 2025-06-02 04:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikeshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_delivered', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_defective', models.BooleanField(default=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.component')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.procurementorder')),
            ],
        ),
    ]
