# Generated by Django 4.2.7 on 2025-06-06 11:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('worker_type', models.CharField(choices=[('skilled', 'Facharbeiter'), ('unskilled', 'Hilfsarbeiter')], max_length=10, verbose_name='Arbeitertyp')),
                ('hourly_wage', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Stundenlohn')),
                ('efficiency', models.IntegerField(default=100, help_text='Effizienz in Prozent (100% = Normal, 150% = sehr effizient)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Effizienz (%)')),
                ('experience_level', models.IntegerField(default=1, help_text='Level 1-10 (höher = erfahrener)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Erfahrungslevel')),
                ('hired_date', models.DateTimeField(auto_now_add=True, verbose_name='Einstellungsdatum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Arbeiter',
                'verbose_name_plural': 'Arbeiter',
                'ordering': ['worker_type', 'name'],
            },
        ),
    ]
