# Generated by Django 4.2.7 on 2025-06-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikeshop', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('transport_cost_home', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transport_cost_foreign', models.DecimalField(decimal_places=2, max_digits=6)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_month', models.IntegerField()),
                ('sale_year', models.IntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_completed', models.BooleanField(default=False)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.producedbike')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.market')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPriceSensitivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_segment', models.CharField(choices=[('cheap', 'Günstig'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('percentage', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.market')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='MarketDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_percentage', models.FloatField()),
                ('bike_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.biketype')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.market')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
        ),
    ]
