# Generated by Django 4.2.11 on 2025-09-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='monthly_volume_capacity',
            field=models.IntegerField(default=200, help_text='Maximum bikes that can be sold per month'),
        ),
        migrations.AddField(
            model_name='market',
            name='price_elasticity_factor',
            field=models.FloatField(default=1.0, help_text='Price sensitivity factor for demand curves'),
        ),
    ]
