# Generated by Django 4.2.11 on 2025-11-05 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0005_worker_tracking_month_worker_tracking_year_and_more'),
        ('sales', '0002_market_monthly_volume_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='city_bike_factor',
            field=models.FloatField(default=1.0, help_text='Multiplier for city/commuter bike demand (0.0-2.0)'),
        ),
        migrations.AddField(
            model_name='market',
            name='green_city_factor',
            field=models.FloatField(default=1.0, help_text='Multiplier for e-bike demand (0.0-2.0, 1.0=neutral, >1.0=higher demand)'),
        ),
        migrations.AddField(
            model_name='market',
            name='location_type',
            field=models.CharField(choices=[('urban', 'Urban (City)'), ('suburban', 'Suburban'), ('rural', 'Rural'), ('mountainous', 'Mountainous'), ('coastal', 'Coastal')], default='urban', help_text='Type of location affecting bike demand', max_length=20),
        ),
        migrations.AddField(
            model_name='market',
            name='mountain_bike_factor',
            field=models.FloatField(default=1.0, help_text='Multiplier for mountain bike demand (0.0-2.0)'),
        ),
        migrations.AddField(
            model_name='market',
            name='road_bike_factor',
            field=models.FloatField(default=1.0, help_text='Multiplier for road/racing bike demand (0.0-2.0)'),
        ),
        migrations.CreateModel(
            name='SalesDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_segment', models.CharField(choices=[('cheap', 'Günstig'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('desired_price', models.DecimalField(decimal_places=2, help_text="Player's desired selling price per bike", max_digits=8)),
                ('transport_cost', models.DecimalField(decimal_places=2, help_text='Transport cost per bike', max_digits=6)),
                ('decision_month', models.IntegerField(help_text='Month when decision was made')),
                ('decision_year', models.IntegerField(help_text='Year when decision was made')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this decision has been processed by market simulation')),
                ('quantity_sold', models.IntegerField(default=0, help_text='How many bikes actually sold')),
                ('actual_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Actual revenue received', max_digits=10)),
                ('unsold_reason', models.CharField(blank=True, help_text="Reason bikes didn't sell (e.g. 'market_oversaturated')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.biketype')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.market')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.gamesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
