# Generated by Django 4.2.11 on 2025-11-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_market_city_bike_factor_market_green_city_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdecision',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, help_text='Transport cost per shipment (one-time cost for delivery to market)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, help_text='Transport cost (only set on first bike of shipment, others have 0)', max_digits=6),
        ),
    ]
