# Generated by Django 4.2.11 on 2025-12-11 12:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0007_make_parameters_dynamic'),
        ('sales', '0004_alter_salesdecision_transport_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketResearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('research_level', models.CharField(choices=[('none', 'No Research'), ('basic', 'Basic Research'), ('advanced', 'Advanced Research'), ('premium', 'Premium Research')], default='none', max_length=20)),
                ('invested_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('actual_demand', models.IntegerField(default=0, help_text='Actual monthly demand (hidden from player)')),
                ('estimated_min', models.IntegerField(default=0, help_text='Minimum estimated demand shown to player')),
                ('estimated_max', models.IntegerField(default=0, help_text='Maximum estimated demand shown to player')),
                ('bike_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_research', to='bikeshop.biketype')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='sales.market')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_research', to='bikeshop.gamesession')),
            ],
            options={
                'ordering': ['-purchased_at'],
                'unique_together': {('session', 'market', 'bike_type')},
            },
        ),
        migrations.CreateModel(
            name='MarketResearchTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('research_level', models.CharField(max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('market_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.marketresearch')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_transactions', to='bikeshop.gamesession')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
